query EducationPage($locale: SiteLocale!) {
    education {
        text(locale: $locale)
        title(locale: $locale)
        seo(locale: $locale) {
            title
            description
        }
    }
}
