query WhyPage($locale: SiteLocale!) {
    why {
        title(locale: $locale)
        text(locale: $locale)
        seo(locale: $locale) {
            title
            description
        }
    }
}
